# Generated by Django 4.1.7 on 2023-03-30 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='participant',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='wish',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
