# Generated by Django 4.1.7 on 2023-03-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_group_description_alter_participant_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='wish',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
