# Generated by Django 4.1.7 on 2023-03-30 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_group_description_alter_participant_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantgroup',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.participant', unique=True),
        ),
    ]
